name: Publish Package to PyPi

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to build from for manual runs"
        required: false
        type: string
      gitrelease:
        description: "Whether to release with a GitHub Release."
        required: true
        type: boolean
        default: true
      thornforge-ref:
        description: "The Git ref of the ThornForge repo to use"
        required: false
        type: string
        default: main
      environment-name:
        description: "The name of the PyPi environment"
        required: false
        type: string
        default: pypi
      environment-project:
        description: "The name of the PyPi project."
        required: false
        type: string

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      ref: ${{ inputs.ref }}
      gitrelease: ${{ inputs.gitrelease }}
      thornforge-ref: ${{ inputs.thornforge-ref }}
      environment: "publish"
      environment-name: ${{ inputs.environment-name }}
      environment-project: ${{ inputs.environment-project }}
