name: Publish Package to PyPi

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to build from for manual runs"
        required: false
        type: string
      gitrelease:
        description: "Whether to release with a GitHub Release."
        required: true
        type: boolean
        default: true
      thornforge-ref:
        description: "The Git ref of the ThornForge repo to use"
        required: false
        type: string
        default: main
      environment-name:
        description: "The name of the PyPi environment"
        required: false
        type: string
        default: pypi
      environment-project:
        description: "The name of the PyPi project."
        required: false
        type: string
  workflow_call:
    inputs:
      ref:
        description: "Git ref to build from"
        required: false
        type: string
      gitrelease:
        description: "Whether to release with a GitHub Release."
        required: true
        type: boolean
        default: true
      thornforge-ref:
        description: "The Git ref of the ThornForge repo to use"
        required: false
        type: string
        default: main
      environment-name:
        description: "The name of the PyPi environment"
        required: false
        type: string
        default: pypi
      environment-project:
        description: "The name of the PyPi project."
        required: false
        type: string

jobs:
  resolve-info:
    uses: Officer-Erik-1K-88/ThornForge/.github/workflows/info.yml@main
    with:
      ref: inputs.ref
      thornforge-ref: inputs.thornforge-ref
      environment-name: inputs.environment-name
      environment-project: inputs.environment-project

  build:
    needs: resolve-info
    permissions:
      contents: read
    uses: ${{ needs.resolve-info.outputs.thornforge-repository }}/./.github/workflows/build.yml@${{ needs.resolve-info.outputs.thornforge-ref }}
    with:
      ref: ${{ needs.resolve-info.outputs.project-ref }}

  publish-pypi:
    name: Publish To PyPI
    needs: [build, resolve-info]
    runs-on: ubuntu-latest
    environment:
      name: needs.resolve-info.outputs.live-environment
      url: https://pypi.org/p/${{ needs.resolve-info.outputs.project-name }}
    permissions:
      id-token: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v7
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: Create GitHub Release
    needs: [publish-pypi, resolve-info]
    if: ${{ github.event_name == 'push' || (contains(fromJSON('["workflow_dispatch", "workflow_call"]'), github.event_name) && inputs.gitrelease) }}
    permissions:
      contents: write
    uses: ${{ needs.resolve-info.outputs.thornforge-repository }}/.github/workflows/release.yml@${{ needs.resolve-info.outputs.thornforge-ref }}
    with:
      ref: ${{ needs.resolve-info.outputs.project-ref }}
