name: Publish Package to Test PyPi

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to build from for manual runs"
        required: false
        type: string
      thornforge-ref:
        description: "The Git ref of the ThornForge repo to use"
        required: false
        type: string
        default: main
      environment-name:
        description: "The name of the TestPyPi environment"
        required: false
        type: string
        default: testpypi
      environment-project:
        description: "The name of the TestPyPi project."
        required: false
        type: string

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      ref: ${{ inputs.ref }}
      gitrelease: false
      thornforge-ref: ${{ inputs.thornforge-ref }}
      environment: "test"
      test-environment-name: ${{ inputs.environment-name }}
      test-environment-project: ${{ inputs.environment-project }}
